name: Update IP List

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 */1 * * *'  # 每1小时运行一次

jobs:
  update-ip-list:
    runs-on: ubuntu-latest
    
    # 关键权限设置
    permissions:
      contents: write  # 必须要有写入权限
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史记录
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # 推荐使用较新版本
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
        
    - name: Run IP collection script
      run: python collect_ips.py
      
    - name: Verify IP list
      run: |
        if [ ! -f "ip.csv" ] || [ ! -s "ip.csv" ]; then
          echo "::error::生成的IP列表为空或文件不存在!"
          exit 1
        fi
        echo "找到 $(wc -l < ip.csv) 个IP地址"
        
    - name: Commit and push changes
      run: |
        # 配置Git
        git config --global user.name "GitHub Actions"
        git config --global user.email "github-actions@example.com"
        
        # 检查是否有变更
        git status
        if git diff --quiet --exit-code; then
          echo "没有检测到文件变更"
          exit 0
        fi
        
        # 提交变更
        git add ip.csv
        git commit -m "自动更新IP列表 [$(date +'%Y-%m-%d %H:%M')]"
        
        # 尝试推送（最多重试3次）
        for i in {1..3}; do
          if git push; then
            echo "推送成功"
            break
          else
            echo "推送失败，重试 $i/3..."
            sleep 5
            git pull --rebase  # 解决可能的冲突
          fi
        done
